version: "3"
services:
  www:
    build: app
    ports:
      - ${PORT-8000}:5000
    user: nobody
    environment:
      DEBUG: 1
    command: python counter.py
    volumes:
      - ./www:/src
  redis:
    image: redis  # il est possible de changer l'image au besoin
    container_name: Contain_Redis
