# Utilisez l'image officielle Redis comme base
FROM redis:latest

# Facultatif : vous pouvez ajouter des métadonnées pour décrire l'image
LABEL maintainer="VotreNom <votre@email.com>"

# Exposez le port Redis (par défaut 6379)
EXPOSE 6379

# Commande pour exécuter Redis Server
CMD ["redis-server"]


